# Generated by Django 5.0.6 on 2024-05-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='module',
            new_name='modules',
        ),
    ]
