# Generated by Django 5.0.6 on 2024-05-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_module_member_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='account_details',
            field=models.TextField(blank=True),
        ),
    ]
