# Generated by Django 5.0.6 on 2024-05-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_license_rate_member_licenses_member_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='adult_with_child_rate',
            field=models.BooleanField(default=False),
        ),
    ]
