# Generated by Django 5.0.6 on 2024-05-15 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_adult_with_child_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='adult_with_child_rate',
        ),
    ]
